id: P000475
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14133
  title: སྦས་དོན་གྱི་ཕྱོགས་ཆ།
  author: ''
  volumes:
    171ab4f66e1548cb9adb49753ac17e37:
      image_group_id: I1KG14323
      title: Volume 1 of sbas don gyi phyogs cha/
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
